FROM python:3.8-slim-buster

ENV INSTALL_PATH /webapp
RUN mkdir -p $INSTALL_PATH

WORKDIR $INSTALL_PATH

COPY requirements.txt requirements.txt

ENV BUILD_DEPS="build-essential" \
  APP_DEPS="curl libpq-dev"

RUN apt-get update \
  && apt-get install -y ${BUILD_DEPS} ${APP_DEPS} --no-install-recommends \
  && pip install -r requirements.txt \
  && rm -rf /var/lib/apt/lists/* \
  && rm -rf /usr/share/doc && rm -rf /usr/share/man \
  && apt-get purge -y --auto-remove ${BUILD_DEPS} \
  && apt-get clean

COPY . .

# CMD gunicorn -b 0.0.0.0:8000 --log-file=- --worker-tmp-dir /dev/shm "__init__:create_app()"
# CMD ["/bin/sh", "-c", "gunicorn -b 0.0.0.0:8000 --log-file=- "webapp.app:create_app("config.settings.DevConfig")""]
# CMD ["gunicorn", "-b", "0.0.0.0:8000", "--log-file=-", "--worker-tmp-dir /dev/shm",  "webapp.app:create_app('config.settings.DevConfig')"]
